### ISSUE TITLE
Propuestas Cargas Docentes

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#101]
- Una vez generada la propuesta, mostrar el formato que esta en la carpeta [\any\carga docente]
- La propuesta tiene que ser validada o rechazada por el usuario administrador, de ser, validada, se vaciara en la table de docentes materias

**Comment by VanessaDelAngel** [comment]
VDA - Falta que funcione el DELETE
VDA - Actualizar GET para que traiga las Materias de asesorias
