### ISSUE TITLE
Propuestas Cargas Docentes

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#106]
- PropuestasCargas
ADD [status INT, comentarios VARCHAR(1000)]
status: [0.-no validada, 1.-validada, 3.-revisada]

Una vez que la propuesta es validada, vaciar los datos sobre docentes materias.

**Comment by eumati** [comment]
@xXLokerXx BACKEND

**Comment by eumati** [comment]
@VanessaDelAngel  FRONTEND

**Comment by VanessaDelAngel** [comment]
Poner Mensaje que advierta que hay que tener grupos activos
