### ISSUE TITLE
Formatos 2

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#111]
@MoarDante @josuevidal @VanessaDelAngel @xXLokerXx 

- Meta: Hacer 25 formatos para el lunes 6 de abril, para la presentacion.

**Comment by MoarDante** [comment]
constaciasdeestudios.pdf

**Comment by josuevidal** [comment]
actadeevaluacion
actadeevaluacion2
actadeevaluacion2recursamiento
actadeevaluacionrecusamiento

**Comment by josuevidal** [comment]
datos necesarios de actadeevaluacion:
nombre del plantel
carrera con clave de la materia
clave del plantel
folio
turno
generacion
grupo
semestre
periodo
docente
asignatura
fecha
numero de lista (ordenado)
matricula
nombre del alumno

**Comment by VanessaDelAngel** [comment]
VDA -  lista de asistencia

**Comment by MoarDante** [comment]
<div class="small-12 columns tituloFormatos">
	<div class="small-2 columns">
		<figure class="logoHistorial"><img src="../../images/SEED.png"></figure>
	</div>
	<div class="small-8 columns">
		<h3> COORDINACIÓN DE ORGANISMOS DESCENTRALIZADOS</h3>
		<h3>ESTATALES DE CECYTED</h3>
		<h4>COLEGIO DE ESTUDIOS CIENTIFICOS Y   TECNOLOGICOS</h4>
		<h4>DEL ESTADO DE DURANGO</h4>
		<h4 class="tituloFondoBase">CONSTANCIA DE INSCRIPCION</h4>	
	</div>
	<div class="small-2 columns">
		<figure><img src="../../images/CECyTED.png"></figure>
	</div>
	<div class="small-3 columns align-top ">
		<figure><img src="../../images/usuario_annon.jpg"></figure>
	</div>
</div>

**Comment by josuevidal** [comment]
datos de acta de evaluación 2

datos que enviare
grupo
materia

datos a recibir
nombre del plantel
carrera con clave
clave del plantel
folio
turno
generación
grupo
semestre
periodo
docente
asignatura
numero de lista del alumno (ordenado)
matricula del alumno
nombre del alumno
calificación de la materia

**Comment by xXLokerXx** [comment]
Constancia de Inscripcion:
contiene folio, generarlo en la BD, guardar el numero de constancias hechas

**Comment by josuevidal** [comment]
constancia de estudios

**Comment by MoarDante** [comment]
clase para contorno de div :  contornoFormatos

**Comment by josuevidal** [comment]
Servicio social carta de baja
servicio social carta de presentación
servicio social carta de aceptación
servicio social informe bimestral

**Comment by josuevidal** [comment]
servicio social baja
datos enviados
alumnos

datos necesarios

fecha
estado del plantel
municipio del plantel
nombre del alumno
numero de control
carrera
semestre
grupo
director del plantel
nombre del plantel

**Comment by josuevidal** [comment]
informe bimestral de actividades

datos enviados
alumno

datos necesarios

plantel del alumno
ubicacion del plantel
nombre del alumno
grupo
asesor del servicio social

**Comment by josuevidal** [comment]
lista de asistencia de recursamientos
datos enviados
grupo

datos necesarios
plantel
clave del plantel
carrera
generacion
folio
grupo
turno
semestre
periodo
materia
docente 
alumnos del grupo con los siguientes datos:
numero de lista, ordenado
matricula
nombre del alumno

**Comment by josuevidal** [comment]
acta de evaluacion parcial
datos enviados
grupos

datos necesarios
nombre del plantel
carrera
clave del plantel
folio
turno
generacion
grupo
semestre
periodo
maestro
materia
todos los alumnos del grupo con los siguientes datos:
numero de lista
numero de control
nombre del alumno

**Comment by josuevidal** [comment]
carta de compromiso de servicio social

datos enviados
alumno

datos necesarios

nombre del alumno
semestre
carrera
plantel del alumno
clave del plantel
calle del plantel
numero de plantel (numero de casa xD)
colonia del plantel
poblacion del plantel
estado del plantel
director del plantel

**Comment by josuevidal** [comment]
tarjeta de control del servicio social
datos enviados
nombre del alumno

datos necesarios
apellido paterno del alumno
apellido materno del alumno
nombre del alumno
edad
sexo
carrera
numero de control del alumno
semestre 
creditos aprobados

**Comment by josuevidal** [comment]
carta de presentacion de servicio social

datos enviados
alumno
datos necesarios

nombre del alumno
numero de control
carrera
director del plantel y ya xD

**Comment by xXLokerXx** [comment]
formatos/GenerarAvanceInscripcion

**Comment by MoarDante** [comment]
frmReportePromedioSemestre [html:x , Js : x, Vali: x ]
frmConcentradoEsolar  [html:x , Js : x, Vali: x ]

**Comment by josuevidal** [comment]
frmReporteEcaFinal y frmReporteEvaParcial les faltan datos, por lo tanto aun no se realizaran
