### ISSUE TITLE
Excel to DB

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#114]
- En base al archivo /querys/Base de datos 1er parcial.xlsx
 * Generar un proceso para subir la informacion a la tabla de calificaciones en el campo de examen

** Hacer primero la prueba con unos cuantos registros

![image](https://cloud.githubusercontent.com/assets/8921806/7124451/94ee33f6-e1ee-11e4-8b53-97b6030d8358.png)

- Agregar el campo de folio a la tabla de calificaciones

**Comment by xXLokerXx** [comment]
Listo el procedimiento, falta probar el enviar datos reales

**Comment by eumati** [comment]
- Verificar que inserte datos
- Generar puntos de control para evitar que el roceso se pare por errores
- Ver cuales alumnos si/no se insertaron, y mostrarlos en una tabla
