### ISSUE TITLE
Validacion de cargas docentes

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#115]
- STATUS [Anterior]
0.- No validada
1.- Validada
2.- Revisada

- STATUS [Actual]
0.- Abierta
1.- Enviada
2.- Validada

- Añadir boton de enviar al formulario de PropuestasCargasDetalles el cual guardara le PropuestaCarga con el "status" 1 (enviada), al obtener este status, esta propuesta ya no poder se modificada. Pada poder cambiar el estatus de 0 a 1, cada una de las materias debe tener asignado un docente.

- En validacion de las propuestas, solo apareceran las propuestas de status 1, la prupuesta se puede rechazar, de ser asi volvera a ser status 0, mostrando los comentarios (si esque tiene) en el formulario de PropuestasCargasDetalles. O puede ser validada, quedando cerrada esta propuesta

- Añadir funcionalidad para cambiar materias de docente
- Añadir a la tabla, el tfoot de totales
 * @VanessaDelAngel 

- Una vez validada la carga docene esta ya no puede volver a ser validada (y no debe poder agregar registros a la base de datos)
 * @VanessaDelAngel 
 * @xXLokerXx

**Comment by VanessaDelAngel** [comment]
Falta agregar el or en el tya de propuestas :rabbit:
