### ISSUE TITLE
Reporteador

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#123]
- Terminar el reporteador

**Comment by OzwaldoC8** [comment]
o.o7

**Comment by VanessaDelAngel** [comment]
* Falta botón de cancelar en el pop de vista previa de reporteador y en el de abrir reporte
 * Marco error al guardar el reporte
* Algunos objetos no se sueltan en su lugar
* En la vista completa no aparece todo el reporte
* Le falta titulo al reporteador

**Comment by eumati** [comment]
Cuando se selecciona un reporte para modificar, se guarden los cambios
