### ISSUE TITLE
Reportes

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#129]
- En base al archivo /any/formatos hechos.xlsx
- Verificar los formatos que faltan y hacerlos

**Comment by VanessaDelAngel** [comment]
Este es lo que tengo registrado que falta, si uno ya esta hecho lo revisan a ver si funciona, si tienen duda en alguno pregunten a ver si hay que hacerlo o todavía no.

 @MoarDante 
 * frmConstanciaReinscripcion
 * frmListadoReguralizaciones
 * frmReporteRegularizaciones
 * frmReporteParciales
 * frmConcentradoEscolar
 * frmExamenRecuperacion 
 * frmExamenRegularizacion
 * frmReporteParciales

@josuevidal 
 * frmSevicioSocialInformeBimestral
 * frmReporteEvaFinal
 * frmReporteEvaParcial
* frmServicioSocialSolicitud

**Comment by josuevidal** [comment]
a infomeBimestral le faltan los siguientes datos:
 plantel
 grupo
a servicioSocialSolicitud solo le faltan unos estilos

a los reportes de de evaFinal y evaParcial le no se han hecho por que faltan las faltas que tuvo el alumno en el parcial
