### ISSUE TITLE
DB Bitacoras

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#138]
- BitacorasPermisos NEW
[idBitacoraPermiso INT, idBitacoraIntegrante INT, fecha DATE, activo INT]

- BitacorasArchivos ADD
 * indicador [1.-Verde, 2.-Amarillo, 3.-Rojo]

- BitacorasForos ADD
 * tipo [1.- especifico, 2.-grupal]
 * idBitacoraIntegranteTo 

- Añadir en
 * [Modelos, Get, Save, Formulario, Vista, Tabla]

**Comment by xXLokerXx** [comment]
Modelos, get, save, tabla y vista, falta formulario, ayudara josue con eso
