### ISSUE TITLE
Titulos y correcciones

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#140]
✓- Quitar el campo de condonacion y descuento, en preinscripciones, ingresosPropiosCobrar
✓- Cambiar titulo del formulario "ingresosPropiosCobrar" de [Ingresos Propios a Cobrar] a [Cobrar Adeudos]
✓- Cambiar titulo del formulario "consultarAdeudos" de [Consulta de Adeudos] a [Consulta de Adeudos por Alumno]
✓- Cambiar titulo del formulario "historicosAdeudos" de [Adeudos] a [Historial de Adeudos por Plantel]
✓- Cambiar titulo del formulario "ingresosPropiosCobrar" de [Ingresos Propios a Cobrar] a [Cobrar Adeudos]

**Comment by xXLokerXx** [comment]
Falta quitar descuento y condonado al formulario de ingresospropioscobrar
