### ISSUE TITLE
Corte de presupuesto

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#143]
- Generar un formulario en el cual se muestre el total de presupuesto que tiene el plantel para que el director efectue un deposito en el banco y poder capturar los datos correspondientes

- Cortes
[idCorte INT, idPlantel INT, banco VARCHAR(500), numCuenta VARCHAR(50), fecha DATE, cantidad NUMBER(18, 2), deposito NUMBER(18,2), status INT]
 * status [1.-Abierto, 2.-Cerrado]

**Comment by xXLokerXx** [comment]
Listo los get, save, vista, modelo y controlador

**Comment by xXLokerXx** [comment]
cortes/ObtenerCorte

**Comment by MoarDante** [comment]
100%
