### ISSUE TITLE
Calificaciones de recuperacion

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#145]
- Generar formulario para capturar calificaciones de parciales de recuperacion

**Comment by xXLokerXx** [comment]
docentes/AlumnosParciales (no se necesita enviar nada)

**Comment by xXLokerXx** [comment]
docentes/GruposRecuperacio (no necesita enviar nada)

**Comment by xXLokerXx** [comment]
docentes/CalificarRecuperacion (Para calificar la recuperacion)

**Comment by VanessaDelAngel** [comment]
VDA - Formulario terminado, falta probarlo junto con promociones
