### ISSUE TITLE
DB Encuestas

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#149]
- Encuestas
[idEncuesta INT, nombre VARCHAR(500)]

- EncuestasPlanteles
[idEncuesta INT, idPlantel INT]

- Categorias
[idCategoria INT, nombre VARCHAR(500), resultado VARCHAR(1000), tipo INT]
 * tipo: 0:no combinada, 1:combinada

- Preguntas
[idPregunta INT, nombre VARCHAR(500)]

- PreguntasEncuesta
[idPreguntaEncuesta INT, idPregunta INT, idEncuesta INT, idCategoria INT]

- DetallesEncuestas
[idDetalleEncuesta INT, idEncuesta INT, condicion VARCHAR(2), valor NUMBER(18,2), total INT, tolerancia INT, combinaciones INT]
 * tolerancia: 1:abierta, 0:cerrada
 * combinaciones: 1:si, 0:no

- Respuestas
[idRespuesta INT, nombre VARCHAR(500)]

- RespuestasDetalles
[idRespuestaDetalle INT, idPreguntaEncuesta INT, idRespuesta INT, peso NUMBER(18, 2)]

- RespuestasAlumnos
[idRespuestaAlumno INT, idRespuestaDetalle INT, idEncuestaAlumno INT, fecha DATE DEFAULT SYSDATE]

- ResultadosAlumnos
[idResultadoAlumno INT, idEncuestaAlumno INT, idCategoria INT]

- EncuestasAlumnos
[idEncuestaAlumno INT, idGrupoAlumno INT, idEncuesta INT, status INT]
 * status: 1:abierta, 2:cerrada

- Combinaciones
[idCombinacion INT, idCategoriaBase INT, idCategoria INT]

**Comment by xXLokerXx** [comment]
Creadas tablas, modelos, vistas, controladores.
Falta checar errores
