### ISSUE TITLE
CT-C Enuestas

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#150]
- Encuestas
[idEncuesta INT, nombre VARCHAR(500)]

- EncuestasPlanteles
[idEncuesta INT, idPlantel INT]

- DetallesEncuestas
[idDetalleEncuesta INT, idEncuesta INT, condicion VARCHAR(2), valor NUMBER(18,2), total INT, tolerancia INT, status INT]
 * tolerancia: 1:abierta, 0:cerrada
 * combinaciones: 1:si, 0:no

**Comment by xXLokerXx** [comment]
encuestas/GuardarEncuesta (para guardar encuestas)

**Comment by VanessaDelAngel** [comment]
VDA - Terminado [✓]
