### ISSUE TITLE
FRM RespuestasAlumnos

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#156]
- RespuestasAlumnos
[idRespuestaAlumno INT, idRespuestaDetalle INT, idEncuestaAlumno INT, fecha DATE DEFAULT SYSDATE]

**Comment by xXLokerXx** [comment]
respuestasAlumnos/PreguntasRespuestas (get de preguntas y sus respsuestas

**Comment by VanessaDelAngel** [comment]
Falta que muestre el nombre del alumno en la encuesta
