### ISSUE TITLE
FRM EncuestasAlumnos

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#158]
- EncuestasAlumnos
[idEncuestaAlumno INT, idGrupoAlumno INT, idEncuesta INT, status INT]
 * status: 1:abierta, 2:cerrada

**Comment by MoarDante** [comment]
![wp_000001](https://cloud.githubusercontent.com/assets/8039668/7421506/8021a3ea-ef4a-11e4-93b7-6bce672ad4af.jpg)

**Comment by MoarDante** [comment]
Grupo
Carrera
Plan


te mandare idPlantel y el semestre

y en el save se asignara una encuesta ya sea por plantel,semestre o grupo

**Comment by xXLokerXx** [comment]
encuestasAlumnos/Encuestas

**Comment by MoarDante** [comment]
te mandare ya sea el plantel,semestre o el grupo y la encuesta que se les asignara según escojan de las 3 opciones anteriores, si escogen grupo se le asignara la encuesta a todos los alumnos de ese grupo, si escogen el semestre le asignaras esa encuesta a todos los grupos de ese semestre y si te mando el plantel se la asignaras a todos los alumnos del plantel
