### ISSUE TITLE
Desempeño

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#161]
![image](https://cloud.githubusercontent.com/assets/8921806/7421245/afa91578-ef48-11e4-99a3-a4aa79bff75c.png)

**Comment by eumati** [comment]
El obtener un punto es que fueron el mejor o estuvieron muy cerdas de serlo.

**Comment by OzwaldoC8** [comment]
o.o7
enterado t.t

**Comment by xXLokerXx** [comment]
No nos fue tan mal, creo...

**Comment by VanessaDelAngel** [comment]
Revisado :)

**Comment by MoarDante** [comment]
washado XD
