### ISSUE TITLE
FRM Grupos bitacoras

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#164]
- Generar formulario para dar de alta grupos y los detalles de los grupos

- BitacorasGrupos
[idBitacoraGrupo INT, nombre VARCHAR(100)]

- BitacorasGruposDetalles
[idBitacoraGrupoDetalle INT, idUsuario INT]

**Comment by xXLokerXx** [comment]
bitacoras/AgregarBitacoraGrupo (save)

**Comment by OzwaldoC8** [comment]
Agregar al get el idBitacoraGrupo para que me regrese los datos por este dato

**Comment by xXLokerXx** [comment]
ya esta
