### ISSUE TITLE
MOD Cortes

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#169]
✓ Añadir campo referencia del deposito en el formulario
✓Quitar el campo de captura de cantidad en el formulario
50%Cambiar los detalles de captura de un deposito, el banco y numero de cuenta se tomaran de la tabla "BancosCuentas"
50% Añadir boton para imprimir la ficha de ayuda de deposito de un corte: Bancos en los que puede hacer el deposito y las posibles cuentas, en base a las tablas [Bancos, BancosCuentas]

**Comment by MoarDante** [comment]
100%
