### ISSUE TITLE
DB Configuraciones y Login

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#172]
- Configuraciones
 * ADD [fechaCorte DATE, statusCorte INT]
 * statusCorte: 1.-espera, 2.-aplicado

- Al ejecutar el SP de login
 * verificar si es el dia de corte
   * SI: verificar el status
     * 1: Cambiar status a 2, y generar un corte para el plantel
     * 2: no hacer nada
   * No: cambiar el status a 1

**Comment by xXLokerXx** [comment]
Hecho
