### ISSUE TITLE
Desempeño

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#174]
![image](https://cloud.githubusercontent.com/assets/8921806/7547106/53b0286e-f5ac-11e4-8b4f-55bc5a37d479.png)

![image](https://cloud.githubusercontent.com/assets/8921806/7547102/35ec2936-f5ac-11e4-9741-40981c86b5d4.png)

**Comment by xXLokerXx** [comment]
Visto

**Comment by VanessaDelAngel** [comment]
Visto

**Comment by OzwaldoC8** [comment]
o.o7 enterado

**Comment by MoarDante** [comment]
![veido](https://cloud.githubusercontent.com/assets/8039668/7547161/58d2715c-f5ad-11e4-8dc0-26a0ccd148ea.jpg)
