### ISSUE TITLE
FRM Historial docentes materias [1]

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#175]
- Hacer un formulario para ver el numero de horas asignadas que tiene cada uno de los docentes
 * Al hacer click en el numero de horas, mostrara el detalle de las materias asignadas

- Seleccionar periodos anteriores y ver el total de horas asignadas
 * Al dar click se mostrara el detalle de las materias asignadas

**Comment by xXLokerXx** [comment]
docentes/historialDocente (get de docentes y sus horas)

**Comment by MoarDante** [comment]
100%
