### ISSUE TITLE
TEST Parciales Recuperación

### ISSUE THREAD

**Issue by VanessaDelAngel** [eumati/res-node#180]
Probar el proceso de parciales de recuperación, esto incluye:
* Asignar parciales de recuperación
* Calificar parciales de recuperación

**Comment by xXLokerXx** [comment]
Se tienen que realizar antes de promocionar al alumno

**Comment by xXLokerXx** [comment]
Realizado correctamente, se tiene que asignar profesor a la materia y luego ir a parciales recuperacion, enseguida se califican dichos parciales y despues se puede promocionar
