### ISSUE TITLE
TEST Horarios

### ISSUE THREAD

**Issue by VanessaDelAngel** [eumati/res-node#188]
Probar el modulo de horarios

**Comment by josuevidal** [comment]
1.- Al momento de buscar en un plantel que al parecer no tiene grupo se queda el letrero de cargando
2.- No guarda la materia  y al momento de modificarlo no funciona

**Comment by OzwaldoC8** [comment]
-ya lo hace
e.e

**Comment by VanessaDelAngel** [comment]
No guarda los horarios
