### ISSUE TITLE
MOD Encuestas

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#202]
- Analizar si se puede:
 * Agregar tipo a "Encuestas", para tenes los tipos de encuestas:
    * Test de orientacion educativa [TOE]
    * Encuestas de seguimiento de egresados [ESE]

- Las "TOE" no sufrirían ningún cambio
- Las "ESE" serian de respuestas abiertas, por lo que no seria necesario agregarles preguntas ni calcular resultados, solo almacenar las respuestas

**Comment by xXLokerXx** [comment]
respuestasAlumnos/GuardarRespuestasSeguimiento

**Comment by VanessaDelAngel** [comment]
VDA - Listo [✓]
