### ISSUE TITLE
Encuestas/Menu

### ISSUE THREAD

**Issue by MoarDante** [eumati/res-node#207]
-resultadosAlumnos - AddMenu - [✓]

GetCtmObtenerResultados

Solo te mandare el idAlumno
y tu me debes mandar las encuestas que tiene asignadas ese alumno

esos son los que me pide la url 
P_IDENCUESTA-NUMBER-IN': '8',
P_SEMESTRE-NUMBER-IN': '',
P_IDGRUPO-NUMBER-IN': '',
P_IDALUMNO-NUMBER-IN': '36',
P_IDUSUARIO-NUMBER-IN': '2',
P_IDPLANTEL-NUMBER-IN': '' },

NUEVA URL

te mandare
idEncustaAlumno

para que me mandes las preguntas de la encuesta seleccionada y las respuestas del alumno

Formularios del Modulo de encuestas que funcionan:

-Combinaciones......................./#combinaciones - AddMenu - [✓]
-Respuestas............................./#respuestas - AddMenu - [✓]
-Preguntas.............................. /#preguntas - AddMenu - [✓]
-Categorías............................./#categorias - AddMenu - [✓]
-Encuestas............................./#encuestas - AddMenu - [✓]
-preguntasEncuestas.........../#preguntasEncuestas - AddMenu - [✓]
-Respuestas Seguimiento.../#respuestasSeguimiento** - AddMenu - [✓]
-tiposEncuestas...................../#tiposEncuestas - AddMenu - [✓]
-RespuestasDetalle.............../#respuestasDetalle - AddMenu - [✓]
-encuestasAlumnos............../#encuestasAlumnos- AddMenu - [✓]
-preguntasEncuestas.........../#AddMenu - [✓]
-respuestasAlumnos............/#respuestasAlumnos- [✓]
Falta Agregar:
- parcialesRecuperacion - AddMenu - [✓]
Modalidades Parciales se repite - DeleteMenu - [✓]

**Comment by OzwaldoC8** [comment]
errores
-- Tipos Infraestructuras
--Modalidades parciales
--Consultar carga docentes y validar propuestas
-- Roles no close
--cambiar datos del usuario
--Alertas motivos error servido.-.
--horarios no close
--calificaciones no close
--historicos alumnos
--reporteador close
--graficas close
--constancia reinscripcion no titulo
--Lista de asistencia
--bitacoras close
--grupos materias optativas close

**Comment by OzwaldoC8** [comment]
url: 'respuestasAlumnos/preguntasRespuestas'
