### ISSUE TITLE
TEST Usuarios

### ISSUE THREAD

**Issue by VanessaDelAngel** [eumati/res-node#212]
Revisar el formulario de usuarios

**Comment by VanessaDelAngel** [comment]
* Agrega nuevo usuario
* Elimina
* Modifica
* Asigna bien los menus

**Comment by VanessaDelAngel** [comment]
Al agregar menús nuevos a la BD marca error cuando los asignas a un usuario

**Comment by eumati** [comment]
Ya que la url de usuarios es de tipo "base", y los datos que se mandan son demasiado grandes, hay que separar la parte custom de la base
 * La parte de roles y planteles hay que ponerlos en otra modal, con una url custom
