### ISSUE TITLE
Revisión De Inputs

### ISSUE THREAD

**Issue by VanessaDelAngel** [eumati/res-node#231]
✓ * Preinscripciones
✓ * Inscripciones
✓ * Calificaciones
✓ * Docentes
✓ * Perfiles
✓ *Docentes Materias
✓ * Planes
✓ * Planes Tronco Común
✓ * Planes Especialidad
✓ * Detalles
✓ * Materias
✓ * Plan Plantel
✓ *Alumnos
✓ *Promociones

**Comment by MoarDante** [comment]
100%
