### ISSUE TITLE
Pruebas de Producción [Administracion de Cortes]

### ISSUE THREAD

**Issue by VanessaDelAngel** [eumati/res-node#306]
* En el menú de arriba no me filtra por estatus cancelado
* Cuando doy clic al registro para ver un detalle se muere (Se supone que eso fue lo que se corrigió hoy pero no se si se subió esa ultima versión)

**Comment by xXLokerXx** [comment]
si se subio, pero en su base de datos no hay datos de corte, por tanto no hay informacion que regrese el procedimiento, se pondra que si no hay datos devuelva un error

**Comment by xXLokerXx** [comment]
listo :+1:
