### ISSUE TITLE
Cambios Pendientes Formularios

### ISSUE THREAD

**Issue by VanessaDelAngel** [eumati/res-node#58]
* Alertas Menús
  * No aparece un registro en cuanto lo agregas tienes que actualizar la pagina
* Avisos
  * No se muestran las fechas
* Infraestructuras
  * Cuando modificas un registro que no tiene salón no lo guarda

**Comment by eumati** [comment]
Infraestructuras [Quitar idPlantel y pasarlo a BACKEND]

**Comment by eumati** [comment]
Listo :)
