### ISSUE TITLE
Cambios [Alumnos]

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#62]
- ComplementariosAlumnos [ADD Columnas]
[docActaNac INT, docCertSec INT, docCurp INT, docCertMed INT, docFotos INT, trabaja INT]

- AlumnosEmpresas [ADD Tabla]
[idAlumnoEmpresa INT, idAlumno INT, nombre VARCHAR(100), domicilio VARCHAR(100), telefono VARCHAR(100), email VARCHAR(100), giro VARCHAR(100), percepcion DECIMAL(18, 2), puesto VARCHAR(100), turno INT]

**Comment by VanessaDelAngel** [comment]
VDA - ComplementariosAlumnos [ADD Columnas] ✓
VDA - AlumnosEmpresas [ADD Tabla] ✓
