### ISSUE TITLE
Grupos Alumnos

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#63]
<div class="row">
			{{#grupos}}
				<div class="small-6 columns blk-grupo" data-id="{{idGrupo}}" data-nombre="{{nombre}}">
					<div class="bloque">
						<span>
							<strong>Grupo {{nombre}}</strong>
						</span>
						<span>Cupo/Alumnos: {{cupo}} / {{totalAlumnos}}</span>
					</div>
					<br/>
				</div>
			{{/grupos}}
		</div>

**Comment by eumati** [comment]
Añadir un registro a historico de alumnos al camiar de grupo

**Comment by xXLokerXx** [comment]
HistoricoAlumnos[Palomita]

**Comment by xXLokerXx** [comment]
Se coloco un ROLLBACK en el procedimiento de SavePeriodos, quitar en el momento que @OzwaldoC8  termine lo de periodos
