### ISSUE TITLE
Validacion de baja de alumnos

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#76]
- Alumnos [UPDATE] [BACKEND]
DROP [motivoBaja, tipoBaja, orientacionEducativa]
** Modificar los campos en la vista y tabla de alumnos, y los "SP" relacionados

- Notificaciones [CREATE]
[idNotificacion INT, idPlantel INT, idUsuario INT]

- Bajas [CREATE]
[idBaja INT, idPlantel INT, idUsuario INT, idAlumno INT, motivoBaja VARCHAR(1000), tipoBaja INT, orientacionEducativa INT, activo INT]
 * tipoBaja: 1.-Personal, 2.-Institucional

- Validaciones [CREATE]
[idValidacion INT, idBaja INT, idUsuario INT, status INT]
status: 0.- no validado, 1.- validado, 2.- rechazado

- Baja:
Al dar de baja a un alumno, se creara un registro en la tabla de "Bajas" guardando los datos de la baja, y en la tabla de "Validaciones" se crearan registros segun el numero de usuarios registrados en la tabla de "Notificaciones"

- Validacion de la baja:
Al dar de baja a un alumno, se mandara una notificacion a los usuarios registrados en la tabla de "Validaciones", posteriormente si todos los usuarios validan la baja, el "activo" del alumno y de la notificacion pasa a ser 0, y se da por cerrado el proceso de baja, si todos los usuarios rechazan la baja, el proceso se cierra y se descarta la baja, limpiando los campos de la tabla de "Alumnos" [motivoBaja, tipoBaja, orientacionEducativa, tipo], mientras que no todos los usuarios validen o rechacen la notificacion, esta sigue abierta (activo = 1).

**Comment by xXLokerXx** [comment]
Alumnos[PALOMITA]
Notificaciones[PALOMITA]
Bajas[PALOMITA]
Validaciones[PALOMITA]
Baja[PALOMITA]

**Comment by VanessaDelAngel** [comment]
VDA - Notificaciones  [✓]
