### ISSUE TITLE
Inscripciones

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#82]
- Poner la validacion de capturar por lo menos un padre, de no ser asi, no dejara inscribir

- Quitar religion, enfermedades cronicas, indigena y otro de indigena

- Quitar requerido en edad y documentos por entregar

**Comment by MoarDante** [comment]
Poner la validacion de capturar por lo menos un padre, de no ser asi, no dejara inscribir  ✓

Quitar religion, enfermedades cronicas, indigena y otro de indigena  ✓

Quitar requerido en edad y documentos por entregar  ✓
