### ISSUE TITLE
Reportes

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#84]
- Poder guardar los reportes

- Poder ver los reportes en un formulario donde aparezcan todos los reportes del plantel asignado al usuario

- Poder asignar reportes a un usuario, para que los pueda ver en un formlario

**Comment by OzwaldoC8** [comment]
'<div class="secciones ui-droppable ui-resizable"><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 14px; left: 32.75px;"><span>Reporte 1   {{first . "actividades" "idInstitucion"}}</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 19px; left: 347.75px;"><span>Texto.. de ejemplo</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 26.875px; left: 134.421875px;"><span>Oz</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 22.875px; left: 453.421875px;"><span>Oz</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div></div><div class="band-reporter ui-droppable ui-resizable"><span class="bind bind-begin isHidden">{{#actividades}}</span><div class="band-reporterch izquierdo derecho superior inferior" data-name="actividades" style="width:100%; height:100%;"><a class="close-obj">×</a><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 22px; left: 15.75px;"><span>Texto...</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 22px; left: 119.75px;"><span>nombre</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="objtxt elementosR" style="top: 44px; left: 295.75px;"><span>Oz</span><a class="close-obj">×</a></div></div><span class="bind bind-end isHidden">{{/actividades}}</span><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div></div>'

**Comment by OzwaldoC8** [comment]
'<div class="secciones ui-droppable ui-resizable"><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 17px; left: 88.75px;"><span>Reporte ejemplo</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="objimg elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 52px; left: 193.328125px; width: 137px; height: 107px;"><img href="#" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAgEASABIAAD/4QwQRXhpZgAATU0AKgAAAAgA…AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/2Q=="><input type="file" class="isHidden"><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 16px; left: 316.75px;"><span>Texto de ejemplo</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 61px; left: 534.75px;"><span>Texto...</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="recuadro-reporter elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 5px; left: 46.484375px; width: 380px; height: 160px;"><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div></div><div class="band-reporter ui-droppable ui-resizable"><span class="bind bind-begin isHidden">{{#actividades}}</span><div class="band-reporterch" data-name="actividades" style="width:100%; height:100%;"><a class="close-obj">×</a><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 38px; left: 149.75px;"><span>D8</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 30px; left: 366.75px;"><span>Texto...</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="objimg elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 21px; left: 506.328125px;"><img href="#" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD//gA7Q1JFQVRPUjogZ2QtanBl…u0nQ9CSxT+2Li6trxvm2R4K7TypGAe1FFFexzwp+7yJ27r/gny3s6tb957aSvrZNWXpof/2Q=="><input type="file" class="isHidden"><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div></div><span class="bind bind-end isHidden">{{/actividades}}</span><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div></div><div class="secciones ui-droppable ui-resizable ui-draggable ui-draggable-handle"><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div><div class="objimg elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 10px; left: 65.328125px; width: 101px; height: 88px;"><img href="#" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAAAAUAAA…bCjGcdfHj/ABP/APdFh/ENH3H3Jb+GO5cejc4mHHjS0ok5z2Ewzne9+vL4M/8ALG+ogwqn/9k="><input type="file" class="isHidden"><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 21px; left: 223.75px;"><span>Texto...</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 16px; left: 400.75px;"><span>Texto...</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div></div><div class="band-reporter ui-droppable ui-resizable"><span class="bind bind-begin isHidden">{{#actividades}}</span><div class="band-reporterch" data-name="actividades" style="width:100%; height:100%;"><a class="close-obj">×</a><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 15px; left: 42.75px;"><span>Texto...</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 28px; left: 235.75px;"><span>nombre</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 37px; left: 404.75px;"><span>activo</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="objimg elementosR ui-resizable ui-draggable ui-draggable-handle selected" style="top: 10px; left: 521.328125px; width: 180px; height: 115px;"><img href="#" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD//gA8Q1JFQVRPUjogZ2QtanBl…15paKAE59PXuf8P6cUc+nYdz/+v8ep4/BaMD09vw9KAE59O47/AOfy78/iUtFGv9L/AIIH/9k="><input type="file" class="isHidden"><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div></div><span class="bind bind-end isHidden">{{/actividades}}</span><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div></div><div class="secciones ui-droppable ui-resizable"><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 33px; left: 52.75px;"><span>Mas textos de prueba</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div><div class="objtxt elementosR ui-resizable ui-draggable ui-draggable-handle" style="top: 17px; left: 194.75px;"><span>AAAAAAAAAAAAA   {{first . "actividades" "nombre"}}</span><a class="close-obj">×</a><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></div></div>'
