### ISSUE TITLE
Docentes

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#85]
- Agregar campos a tabla y formulario:
[**profordems INT, certidems INT, maestria VARCHAR(500), doctorado VARCHAR(500), licencitaura VARCHAR(500), otros estudios (1000), *up_maestria VARCHAR(500), *up_doctorado VARCHAR(500), *up_licenciatura VARCHAR(500), *up_otro VARCHAR(500)]

* Archivos
** checkbox

**Comment by xXLokerXx** [comment]
Se cambiron la BD, el modelo, los procedimientos y las vistas
