### ISSUE TITLE
Validaciones de bajas

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#91]
- Quitar la columna de usuario

- Cambiar el titulo de validaciones por Autorizacion de baja

- Mostrar el motivo de la baja de cada alumno

- Poner una modal que se muestre cuando se de click al alumno el cual mostrara el historial academico

- Los usuarios de tipo OE, podran dejar un comentario en cada una de las bajas

- Mostrar en cada una de las validaciones, los comentarios hechos por los usuarios de OE

- En caso de que la validacion halla sido rechazada, hay que capturar el motivo por el cual fue rechazada

**OE: Orientacion Educativa

**Comment by xXLokerXx** [comment]
BajasComentarios
[idBajaComentario INT, idAlumno INT, idBaja INT, comenteario VARCHAR(2000))

Validaciones ADD
[motivo VARCHAR(2000)]

**Comment by eumati** [comment]
/historicosAlumnos/GruposDocentes
**idAlumno
