### ISSUE TITLE
Bajas

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#92]
- Del combo de tipo, quitar requerido y cambiar el texto por motivo

- Cambiar el texto de movito por descripcion

- Si el motivo es personal, el combobox de OE, tiene que estar checked por fuerza

- Al dar de baja un alumno, mandar una notificacion a todos los usuarios de tipo OE

**OE: Orientacion Educativa

**Comment by xXLokerXx** [comment]
Crear tabla nueva para guardar a los usuarios de tipo 6 (OE)
BajasOrientacion
[idBajaOrientacion INT, idUsuario INT, idBaja INT, activo INT]
