### ISSUE TITLE
Formatos

### ISSUE THREAD

**Issue by eumati** [eumati/res-node#95]
En la carpeta de formatos, estan cinco pdf los cuales hay que pasar a formularios donde muestre esa informacion.

[@VanessaDelAngel, @MoarDante, @josuevidal ]

**Comment by xXLokerXx** [comment]
"idAlumno"
"idPlan"
"idPlantel"
"idCarrera"
"matricula",
"generacion",
"idGrupo"
"semestre"
"idTurno"
"clave"
"idPeriodo"
"fechaActual"
"idMateria"
"promedio"
"asistencia",
"dKeyidAlumno",
"dKeyidGrupo",
"dKeyidTurno",
"dKeyidPlantel",
"dKeyidPeriodo"
"dKeyidMateria"

**Comment by eumati** [comment]
- Lista de asistencias:
 * num, matricula, nombre, clavePlantel, grupo, semestre, turno, materia, carrera

**Comment by xXLokerXx** [comment]
-hostorial academico
* idMateria, promedio, semestre,idPeriodo,
       idAlumno, matricula, curp, dKeyidAlumno,
       idPlantel, clave, dKeyidPlantel,
       idCarrera, clave, dKeyidCarrera
 * URL: formatos/GenerarHistorialAcademico

**Comment by xXLokerXx** [comment]
- REDI
 * idAlumno, matricula, sexo, fechaNacimiento, idSecundaria,
           dKeyidAlumno, dKeyidSecundaria
 * URL: formatos/GenerarRedi

**Comment by MoarDante** [comment]
Rutas para logos de los formatos
<img src="../../images/SEED.png">

<img src="../../images/CECyTED.png">

**Comment by VanessaDelAngel** [comment]
VDA - BOLETASCEFE-  Falta director de plantel y promedio

**Comment by eumati** [comment]
@VanessaDelAngel, @josuevidal, @MoarDante, @xXLokerXx Verificar que los formatos tengan todos los datos, que vienen en el PDF

**Comment by josuevidal** [comment]
en lista de asistencia faltan los siguientes datos:
plantel
generacion
periodo
docente

y los estilos

**Comment by MoarDante** [comment]
En el formato de Historial Académico falta poner la fecha con letra en el formato
