### ISSUE TITLE
Materias Optativas (2)

### ISSUE THREAD

**Issue by xXLokerXx** [eumati/res-node#96]
MateriasOptativasPlanteles [NEW]
[idMateriaOptativaPlantel INT, idPlantel INT, idMateriaOptativa INT, activo INT]

AlumnosOptativas [NEW]
[idAlumnoOptativa INT, idAlumnoMateria INT, idMateriaOptativaPlatel INT, activo INT]

GruposVirtuales [NEW]
[idGrupoVirtual INT, nombre VARCHAR(3), idPlan INT, idPeriodo INT, semestre IINT, cupo INT, activo INT]

Materias [ADD]
[optativa INT [1|0]]

DocentesGruposVirtuales [NEW]
[idDocenteGrupoVirtual INT, idDocente INT, idGrupoVirtual INT]

GruposVirtualesOptativos [NEW]
[idGrupoOptativo INT, idDocenteGrupoVirtual INT, idAlumnoOptativa INT]

**Comment by xXLokerXx** [comment]
Falta generar el formulario de GruposVirtualesOptativos

**Comment by VanessaDelAngel** [comment]
VDA - MateriasOptativasPlanteles [✓]
VDA- AlumnosOptativas [Revisar]
  * Cuando te trae un grupo donde ya guardaste registros no te trae las materias guardadas
  * Se puede asignar la misma materia varias veces a un alumno
VDA - GruposVirtuales [Revisar]
  *Marca error cuando cargo la pagina
